dotenv: .env
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'

networks:
  default: development
  mainnet-fork:
    eth_usd_price_fee: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'

wallets:
  from_key: ${PRIVATE_KEY}